services:
  api:
    container_name: api_container
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "3000:8000"
    depends_on:
      - mongodb
    networks:
      - api_network

  mongodb:
    image: mongo:8.0
    container_name: mongodb_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - api_network
    restart: unless-stopped

volumes:
  mongo_data:

networks:
  api_network:
    driver: bridge